# -*- coding: utf-8 -*-
"""Cópia de krea_2_turbo_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171k3iE2DlKKUJk_yZzj_aA_vMzYR6hHP

⚙️ Cell 1 — Setup do Ambiente
"""

# ⚙️ Cell 1 — Setup Completo do Ambiente (Corrigido)
import os, sys, gc

# Remove apenas TensorFlow (não mexe no NumPy)
for mod in list(sys.modules):
    if 'tensorflow' in mod or 'tf' == mod:
        del sys.modules[mod]
gc.collect()

os.chdir('/content')
print('=== Advanced Multi-Model Image Studio — Setup ===')

# Instala/atualiza dependências
!pip install -q --upgrade pip
!pip install -q --timeout 120 --upgrade "diffusers>=0.30.0" "transformers>=4.44.0" "accelerate" "huggingface_hub" "safetensors"
!pip install -q --timeout 120 mmgp gradio requests

# Clona Wan2GP
if not os.path.exists('Wan2GP'):
    !git clone -q https://github.com/DeepBeepMeep/Wan2GP.git
    print('✅ Wan2GP clonado.')

# Instala dependências do Wan2GP
!pip install -q --timeout 120 -r Wan2GP/requirements.txt

# Patch do krea2_main.py para float16 (T4)
_kp = 'Wan2GP/models/krea2/krea2_main.py'
if os.path.exists(_kp):
    with open(_kp, 'r') as _f:
        _src = _f.read().replace('\r\n', '\n')
    _ch = False
    if 'dtype = torch.bfloat16' in _src:
        _src = _src.replace('dtype = torch.bfloat16', '# dtype = torch.bfloat16  # patched')
        _ch = True
    _old_tf = 'offload.load_model_data(transformer, model_filename, writable_tensors=False, preprocess_sd=preprocess_sd, default_dtype=dtype)'
    _new_tf = 'def tf_preprocess(sd):\n    sd = preprocess_sd(sd)\n    return {k: v.to(dtype) if (isinstance(v, torch.Tensor) and v.is_floating_point()) else v for k, v in sd.items()}\noffload.load_model_data(transformer, model_filename, writable_tensors=False, preprocess_sd=tf_preprocess, default_dtype=dtype)'
    if _old_tf in _src:
        _src = _src.replace(_old_tf, _new_tf); _ch = True
    _old_te = 'offload.load_model_data(text_encoder.language_model, text_encoder_filename, modelPrefix="language_model", writable_tensors=False, default_dtype=dtype)'
    _new_te = 'def te_preprocess(sd):\n    return {k: v.to(dtype) if (isinstance(v, torch.Tensor) and v.is_floating_point()) else v for k, v in sd.items()}\noffload.load_model_data(text_encoder.language_model, text_encoder_filename, modelPrefix="language_model", writable_tensors=False, preprocess_sd=te_preprocess, default_dtype=dtype)'
    if _old_te in _src:
        _src = _src.replace(_old_te, _new_te); _ch = True
    _old_vae = 'offload.load_model_data(vae, filename, writable_tensors=False, default_dtype=dtype)'
    _new_vae = 'def vae_preprocess(sd):\n    return {k: v.to(dtype) if (isinstance(v, torch.Tensor) and v.is_floating_point()) else v for k, v in sd.items()}\noffload.load_model_data(vae, filename, writable_tensors=False, preprocess_sd=vae_preprocess, default_dtype=dtype)'
    if _old_vae in _src:
        _src = _src.replace(_old_vae, _new_vae); _ch = True
    if _ch:
        with open(_kp, 'w') as _f:
            _f.write(_src)
        print('✅ krea2_main.py patched para float16.')

os.makedirs('/content/Wan2GP/models/civitai', exist_ok=True)

print("\n✅ Setup completo! Execute a Cell 2.")

"""🧠 Cell 2 — Gera o aplicativo completo (advanced_app.py)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile advanced_app.py
# import os, sys, json, gc, time, random, traceback, inspect, shutil, re, requests
# from pathlib import Path
# 
# os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
# 
# class _TFBlocker:
#     def find_module(self, name, path=None):
#         if name == "tensorflow" or name.startswith("tensorflow."):
#             return self
#     def load_module(self, name):
#         raise ImportError("TensorFlow blocked to save RAM")
# 
# sys.meta_path.insert(0, _TFBlocker())
# 
# BASE_DIR = "/content"
# WAN2GP_DIR = "/content/Wan2GP"
# REGISTRY_PATH = "/content/models_registry.json"
# MODELS_DIR = os.path.join(WAN2GP_DIR, "models")
# CIVITAI_DIR = os.path.join(MODELS_DIR, "civitai")
# 
# Path(MODELS_DIR).mkdir(parents=True, exist_ok=True)
# Path(CIVITAI_DIR).mkdir(parents=True, exist_ok=True)
# 
# if os.path.exists(WAN2GP_DIR):
#     os.chdir(WAN2GP_DIR)
# 
# os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb:128,garbage_collection_threshold:0.5"
# os.environ["TOKENIZERS_PARALLELISM"] = "false"
# os.environ["MALLOC_TRIM_THRESHOLD_"] = "0"
# 
# import torch, gradio as gr
# from PIL import Image
# from huggingface_hub import HfApi, hf_hub_download, snapshot_download, login
# 
# STATE = {
#     "config": None, "backend": None, "pipe": None,
#     "krea_model": None, "loaded": False,
#     "lora_name": None, "lora_scale": 0.0,
# }
# 
# STYLES = ["None", "Cinematic", "Photographic", "Anime", "Cyberpunk", "Fantasy"]
# COMMON_IGNORE = ["*.msgpack", "*.h5", "*.bin", "*.ckpt", "*.pt", "*.non_ema*"]
# 
# DEFAULT_REGISTRY = {
#     "Krea-2-Turbo (Wan2GP)": {
#         "label": "Krea-2-Turbo (Wan2GP)", "repo": "DeepBeepMeep/krea-2",
#         "backend": "wan2gp_krea2", "folder_name": "krea2-turbo",
#         "base_model_type": "krea2_turbo", "model_type": "krea2_turbo",
#         "dtype": "float16", "vae_dtype": "float16", "quantize_transformer": False,
#         "attention": "sdpa", "guide_scale": 0.0,
#         "supports_negative": True, "supports_guidance": True, "cpu_offload": "mmgp",
#         "steps": {"min": 1, "max": 12, "default": 8},
#         "images": {"min": 1, "max": 2, "default": 1},
#         "resolutions": ["1024px (Standard)", "1536px (High)"],
#         "default_resolution": "1024px (Standard)",
#         "aspect_ratios": ["16:9 Landscape", "9:16 Portrait", "1:1 Square", "4:3 Standard", "3:4 Portrait"],
#         "default_aspect_ratio": "16:9 Landscape",
#         "styles": STYLES,
#         "offload": {"profile_no": 2, "pinnedMemory": False, "asyncTransfers": False,
#                     "budgets": {"transformer": 10000, "text_encoder": 4000, "vae": 1500, "*": 500}},
#         "paths": {
#             "transformer": f"{MODELS_DIR}/Krea2Turbo_quanto_bf16_int8.safetensors",
#             "text_encoder": f"{MODELS_DIR}/Qwen3-VL-4B-Instruct/Qwen3-VL-4B-Instruct_quanto_bf16_int8.safetensors",
#             "vae": f"{MODELS_DIR}/qwen_vae.safetensors",
#             "vae_config": f"{MODELS_DIR}/qwen_vae_config.json"
#         },
#         "warning": "Krea-2-Turbo usa Wan2GP INT8."
#     },
#     "FLUX.1 [schnell]": {
#         "label": "FLUX.1 [schnell]", "repo": "black-forest-labs/FLUX.1-schnell",
#         "backend": "auto", "folder_name": "flux1-schnell", "dtype": "float16",
#         "cpu_offload": "sequential", "use_safetensors": True,
#         "supports_negative": False, "supports_guidance": True, "guide_scale": 0.0,
#         "steps": {"min": 1, "max": 4, "default": 4},
#         "images": {"min": 1, "max": 1, "default": 1},
#         "resolutions": ["768px (Low VRAM)", "1024px (Standard)"],
#         "default_resolution": "768px (Low VRAM)",
#         "aspect_ratios": ["1:1 Square", "16:9 Landscape", "9:16 Portrait"],
#         "default_aspect_ratio": "1:1 Square",
#         "styles": STYLES, "ignore_patterns": COMMON_IGNORE,
#         "warning": "FLUX.1 é pesado. No T4, use 768px."
#     },
#     "SDXL Lightning": {
#         "label": "SDXL Lightning", "repo": "ByteDance/SDXL-Lightning",
#         "backend": "auto", "folder_name": "sdxl-lightning", "dtype": "float16",
#         "cpu_offload": "model", "use_safetensors": True,
#         "supports_negative": True, "supports_guidance": True, "guide_scale": 0.0,
#         "steps": {"min": 2, "max": 8, "default": 4},
#         "images": {"min": 1, "max": 1, "default": 1},
#         "resolutions": ["512px (Fast)", "768px (Balanced)", "1024px (High)"],
#         "default_resolution": "768px (Balanced)",
#         "aspect_ratios": ["1:1 Square", "16:9 Landscape", "9:16 Portrait", "4:3 Standard", "3:4 Portrait"],
#         "default_aspect_ratio": "1:1 Square",
#         "styles": STYLES, "ignore_patterns": COMMON_IGNORE,
#         "warning": "SDXL Lightning é rápido."
#     },
#     "SDXL Turbo": {
#         "label": "SDXL Turbo", "repo": "stabilityai/sdxl-turbo",
#         "backend": "auto", "folder_name": "sdxl-turbo", "dtype": "float16",
#         "cpu_offload": "model", "use_safetensors": True,
#         "supports_negative": True, "supports_guidance": True, "guide_scale": 0.0,
#         "steps": {"min": 1, "max": 4, "default": 2},
#         "images": {"min": 1, "max": 2, "default": 1},
#         "resolutions": ["512px (Turbo)", "768px (Balanced)"],
#         "default_resolution": "512px (Turbo)",
#         "aspect_ratios": ["1:1 Square", "16:9 Landscape", "9:16 Portrait", "4:3 Standard", "3:4 Portrait"],
#         "default_aspect_ratio": "1:1 Square",
#         "styles": STYLES, "ignore_patterns": COMMON_IGNORE,
#         "warning": "SDXL Turbo funciona melhor em 512px."
#     }
# }
# 
# def load_registry():
#     if not os.path.exists(REGISTRY_PATH):
#         save_registry(DEFAULT_REGISTRY)
#         return DEFAULT_REGISTRY.copy()
#     try:
#         with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
#             reg = json.load(f)
#         if not isinstance(reg, dict) or len(reg) == 0:
#             save_registry(DEFAULT_REGISTRY)
#             return DEFAULT_REGISTRY.copy()
#         return reg
#     except Exception:
#         save_registry(DEFAULT_REGISTRY)
#         return DEFAULT_REGISTRY.copy()
# 
# def save_registry(registry):
#     with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
#         json.dump(registry, f, indent=2, ensure_ascii=False)
# 
# def registry_choices():
#     return list(load_registry().keys())
# 
# def refresh_model_dropdown():
#     choices = registry_choices()
#     return gr.update(choices=choices, value=choices[0] if choices else None)
# 
# def get_torch_dtype(name):
#     if name == "float16": return torch.float16
#     if name == "bfloat16": return torch.bfloat16
#     if name == "float32": return torch.float32
#     return torch.float16
# 
# api = HfApi()
# 
# def hf_login(token):
#     token = (token or "").strip()
#     if not token: return "Nenhum token informado."
#     try:
#         login(token=token, add_to_git_credential=False)
#         return "Login no Hugging Face realizado."
#     except Exception as e:
#         return "Falha no login HF: " + str(e)
# 
# def repo_exists(repo):
#     try:
#         api.repo_info(repo)
#         return True
#     except Exception:
#         return False
# 
# def list_repo_files_safe(repo):
#     try:
#         return list(api.list_repo_files(repo))
#     except Exception:
#         return []
# 
# def pick_repo_for_t4(cfg):
#     candidates = []
#     if cfg.get("t4_repo"): candidates.append(cfg["t4_repo"])
#     candidates.extend(cfg.get("t4_repo_candidates", []))
#     if cfg.get("repo"): candidates.append(cfg["repo"])
#     seen = []
#     for c in candidates:
#         if c and c not in seen:
#             seen.append(c)
#             if repo_exists(c): return c
#     return cfg.get("repo")
# 
# def detect_backend(repo):
#     if not repo: return "unknown"
#     if repo == "DeepBeepMeep/krea-2": return "wan2gp_krea2"
#     files = list_repo_files_safe(repo)
#     if not files: return "unknown"
#     if "model_index.json" in files: return "diffusers"
#     if any("Krea2Turbo" in f for f in files): return "wan2gp_krea2"
#     if any(f.lower().endswith((".safetensors", ".ckpt", ".pt")) for f in files): return "single_file"
#     return "unknown"
# 
# def download_krea(cfg):
#     REPO = cfg.get("repo", "DeepBeepMeep/krea-2")
#     QWEN_IMG_REPO = "DeepBeepMeep/Qwen_image"
#     def dl(repo, filename, dest_dir, dest_name=None):
#         Path(dest_dir).mkdir(parents=True, exist_ok=True)
#         name = dest_name or os.path.basename(filename)
#         fp = os.path.join(dest_dir, name)
#         if os.path.exists(fp):
#             print("  OK " + name + " already downloaded"); return
#         print("  DOWN " + name + " ...")
#         hf_hub_download(repo_id=repo, filename=filename, local_dir=dest_dir)
#         tmp = os.path.join(dest_dir, filename)
#         if os.path.exists(tmp) and os.path.abspath(tmp) != os.path.abspath(fp):
#             os.makedirs(os.path.dirname(fp), exist_ok=True)
#             shutil.move(tmp, fp)
#         print("  OK " + name)
#     dl(REPO, "Krea2Turbo_quanto_bf16_int8.safetensors", MODELS_DIR)
#     TE = "Qwen3-VL-4B-Instruct"
#     te_files = ["Qwen3-VL-4B-Instruct_quanto_bf16_int8.safetensors", "config.json", "tokenizer.json", "tokenizer_config.json", "chat_template.jinja", "preprocessor_config.json"]
#     for f in te_files:
#         dl(REPO, TE + "/" + f, os.path.join(MODELS_DIR, TE), dest_name=f)
#     for f in ["qwen_vae.safetensors", "qwen_vae_config.json"]:
#         dl(QWEN_IMG_REPO, f, MODELS_DIR)
#     cache_dir = os.path.join(MODELS_DIR, ".cache")
#     if os.path.exists(cache_dir):
#         try: shutil.rmtree(cache_dir)
#         except Exception: pass
# 
# def download_diffusers(cfg):
#     selected_repo = cfg.get("selected_repo") or cfg.get("repo")
#     if not selected_repo: raise ValueError("Repo nao definido para modelo Diffusers.")
#     folder_name = cfg.get("folder_name", "diffusers-model")
#     local_dir = os.path.join(MODELS_DIR, folder_name)
#     cfg["model_path"] = local_dir
#     if os.path.exists(os.path.join(local_dir, "model_index.json")):
#         print("  OK Modelo Diffusers ja baixado em " + local_dir); return
#     print("  DOWN Baixando " + selected_repo + " para " + local_dir + " ...")
#     snapshot_download(repo_id=selected_repo, local_dir=local_dir, ignore_patterns=cfg.get("ignore_patterns", COMMON_IGNORE))
#     if not os.path.exists(os.path.join(local_dir, "model_index.json")):
#         print("  WARN model_index.json nao encontrado.")
# 
# def download_single_file(cfg):
#     selected_repo = cfg.get("selected_repo") or cfg.get("repo")
#     if not selected_repo: raise ValueError("Repo nao definido para modelo single-file.")
#     folder_name = cfg.get("folder_name", "single-file-model")
#     local_dir = os.path.join(MODELS_DIR, folder_name)
#     Path(local_dir).mkdir(parents=True, exist_ok=True)
#     files = list_repo_files_safe(selected_repo)
#     candidates = [f for f in files if f.lower().endswith((".safetensors", ".ckpt", ".pt"))]
#     if not candidates: raise ValueError("Nenhum arquivo .safetensors/.ckpt/.pt encontrado.")
#     remote_file = candidates[0]
#     local_path = os.path.join(local_dir, os.path.basename(remote_file))
#     if os.path.exists(local_path):
#         cfg["model_path"] = local_path
#         print("  OK " + os.path.basename(remote_file) + " ja existe."); return
#     print("  DOWN Baixando " + remote_file + " ...")
#     hf_hub_download(repo_id=selected_repo, filename=remote_file, local_dir=local_dir)
#     cfg["model_path"] = local_path
#     print("  OK " + os.path.basename(remote_file))
# 
# def parse_civitai_url(url_or_id):
#     if url_or_id.isdigit(): return url_or_id
#     m = re.search(r'civitai\.com/models/(\d+)', url_or_id)
#     if m: return m.group(1)
#     m = re.search(r'api/v1/models/(\d+)', url_or_id)
#     if m: return m.group(1)
#     return None
# 
# def download_from_civitai(url_or_id, token):
#     model_id = parse_civitai_url(url_or_id)
#     if not model_id: raise ValueError("URL ou ID do Civitai invalido.")
#     api_url = "https://civitai.com/api/v1/models/" + model_id
#     headers = {}
#     if token and token.strip(): headers["Authorization"] = "Bearer " + token.strip()
#     print("CONSULTANDO API do Civitai para o modelo ID: " + model_id + "...")
#     response = requests.get(api_url, headers=headers)
#     if response.status_code != 200:
#         raise ValueError("Falha ao consultar Civitai (Status " + str(response.status_code) + ").")
#     data = response.json()
#     model_name = data.get("name", "unknown_model")
#     versions = data.get("modelVersions", [])
#     if not versions: raise ValueError("Nenhuma versao encontrada.")
#     latest_version = versions[0]
#     base_model = latest_version.get("baseModel", "unknown")
#     files = latest_version.get("files", [])
#     if not files: raise ValueError("Nenhum arquivo encontrado.")
#     checkpoints = [f for f in files if f.get("type") == "Model"]
#     if not checkpoints:
#         loras = [f for f in files if f.get("type") == "LoRA"]
#         if loras:
#             raise ValueError("Este modelo e um LoRA, nao um Checkpoint. Use a secao LoRA.")
#         raise ValueError("Nenhum arquivo do tipo 'Model' encontrado.")
#     checkpoints.sort(key=lambda x: x.get("sizeKB", 0), reverse=True)
#     target_file = checkpoints[0]
#     download_url = target_file.get("downloadUrl")
#     file_name = target_file.get("name", "model.safetensors")
#     if not download_url: raise ValueError("URL de download nao encontrada.")
#     safe_name = re.sub(r'[^\w\-.]', '_', file_name)
#     local_path = os.path.join(CIVITAI_DIR, safe_name)
#     if os.path.exists(local_path):
#         print("  OK " + safe_name + " ja existe.")
#         return local_path, base_model, model_name
#     size_gb = target_file.get('sizeKB', 0) / 1024 / 1024
#     print("  DOWN Baixando " + safe_name + " (" + "{:.2f}".format(size_gb) + " GB)...")
#     print("     Base Model: " + base_model)
#     with requests.get(download_url, headers=headers, stream=True) as r:
#         r.raise_for_status()
#         with open(local_path, 'wb') as f:
#             for chunk in r.iter_content(chunk_size=8192):
#                 f.write(chunk)
#     print("  OK " + safe_name + " baixado.")
#     return local_path, base_model, model_name
# 
# def ensure_downloaded(cfg):
#     backend = cfg.get("backend", "auto")
#     selected_repo = pick_repo_for_t4(cfg)
#     cfg["selected_repo"] = selected_repo
#     if backend in [None, "", "auto"]:
#         backend = detect_backend(selected_repo)
#         cfg["backend"] = backend
#     if backend == "wan2gp_krea2": download_krea(cfg)
#     elif backend == "diffusers": download_diffusers(cfg)
#     elif backend == "single_file": download_single_file(cfg)
#     else: raise ValueError("Backend desconhecido: " + str(backend))
#     return cfg
# 
# def unload_current_model():
#     for key in ["pipe", "krea_model"]:
#         if STATE.get(key) is not None:
#             try: del STATE[key]
#             except Exception: pass
#     STATE["pipe"] = None
#     STATE["krea_model"] = None
#     STATE["config"] = None
#     STATE["backend"] = None
#     STATE["loaded"] = False
#     STATE["lora_name"] = None
#     STATE["lora_scale"] = 0.0
#     gc.collect()
#     torch.cuda.empty_cache()
# 
# def load_diffusers(cfg):
#     from diffusers import DiffusionPipeline
#     model_path = cfg.get("model_path") or cfg.get("selected_repo") or cfg.get("repo")
#     if not os.path.isdir(model_path):
#         model_path = cfg.get("selected_repo") or cfg.get("repo")
#     else:
#         if not os.path.exists(os.path.join(model_path, "model_index.json")):
#             fallback_repo = cfg.get("selected_repo") or cfg.get("repo")
#             if fallback_repo: model_path = fallback_repo
#     dtype = get_torch_dtype(cfg.get("dtype", "float16"))
#     load_kwargs = {"torch_dtype": dtype, "low_cpu_mem_usage": True}
#     if cfg.get("use_safetensors", True): load_kwargs["use_safetensors"] = True
#     try:
#         pipe = DiffusionPipeline.from_pretrained(model_path, **load_kwargs)
#     except Exception as e:
#         load_kwargs.pop("use_safetensors", None)
#         pipe = DiffusionPipeline.from_pretrained(model_path, **load_kwargs)
#     offload_mode = cfg.get("cpu_offload", "model")
#     if offload_mode == "sequential":
#         try: pipe.enable_sequential_cpu_offload()
#         except Exception:
#             try: pipe.enable_model_cpu_offload()
#             except Exception: pipe.to("cuda")
#     elif offload_mode == "model":
#         try: pipe.enable_model_cpu_offload()
#         except Exception: pipe.to("cuda")
#     else:
#         try: pipe.to("cuda")
#         except Exception: pass
#     try: pipe.enable_vae_tiling()
#     except Exception: pass
#     try: pipe.enable_vae_slicing()
#     except Exception: pass
#     STATE["pipe"] = pipe
#     STATE["backend"] = "diffusers"
#     STATE["loaded"] = True
# 
# def detect_civitai_family(base_model, model_path):
#     b = (base_model or "").lower()
#     p = (model_path or "").lower()
#     if "flux" in b or "flux" in p: return "flux"
#     if "sd 3" in b or "sd3" in b: return "sd3"
#     if "animagine" in b or "animagine" in p: return "sdxl"
#     if "anima" in b: return "anima"
#     if any(k in b for k in ["sdxl", "pony", "illustrious", "noobai"]): return "sdxl"
#     if any(k in p for k in ["pony", "illustrious", "noobai", "animagine", "sdxl"]): return "sdxl"
#     if "chroma" in b: return "chroma"
#     if "auraflow" in b: return "auraflow"
#     if "hidream" in b: return "hidream"
#     if "hunyuan" in b: return "hunyuan"
#     if "ernie" in b: return "ernie"
#     if "grok" in b: return "grok"
#     if "z-image" in b or "zimage" in b: return "zimage"
#     if "lumina" in b: return "lumina"
#     if "sd 2" in b: return "sd2"
#     return "sd15"
# 
# def _unsupported_family(family, base_model):
#     msgs = {
#         "grok": "Grok (xAI) e um modelo hospedado SEM pesos abertos. Nao pode rodar localmente.",
#         "ernie": "Baidu ERNIE-Image (8B DiT) nao tem single-file estavel no Diffusers e e pesado demais para a T4.",
#         "hidream": "HiDream (17B) excede a capacidade da T4.",
#         "hunyuan": "Hunyuan-DiT nao tem suporte single-file no Diffusers.",
#         "lumina": "Lumina nao tem suporte single-file no Diffusers.",
#         "auraflow": "AuraFlow (6.8B) nao tem pipeline single-file estavel e e pesado para a T4.",
#         "anima": "Anima (CircleStone Labs, 2B) NAO e SDXL. Checkpoints single-file exigem ComfyUI/Forge Neo; suporte Diffusers e experimental.",
#     }
#     return msgs.get(family, "Base model nao suportado: " + str(base_model))
# 
# def load_single_file(cfg):
#     from diffusers import StableDiffusionXLPipeline, StableDiffusionPipeline, AutoencoderKL
#     from transformers import CLIPTextModel, CLIPTokenizer, CLIPTextModelWithProjection
#     model_path = cfg.get("model_path")
#     base_model = cfg.get("base_model_type", "unknown")
#     if not model_path or not os.path.exists(model_path):
#         raise FileNotFoundError("Arquivo single-file nao encontrado.")
#     dtype = get_torch_dtype(cfg.get("dtype", "float16"))
#     is_st = model_path.lower().endswith(".safetensors")
#     family = detect_civitai_family(base_model, model_path)
#     print("FAMILIA detectada: " + family + " (baseModel: " + str(base_model) + ")")
#     pipe = None
#     if family == "flux":
#         from diffusers import FluxPipeline
#         pipe = FluxPipeline.from_single_file(model_path, torch_dtype=dtype, use_safetensors=is_st)
#     elif family == "sd3":
#         from diffusers import StableDiffusion3Pipeline
#         try:
#             pipe = StableDiffusion3Pipeline.from_single_file(model_path, torch_dtype=dtype, use_safetensors=is_st, safety_checker=None, requires_safety_checker=False)
#         except Exception as e:
#             raise RuntimeError("SD3/SD3.5 single-file falhou. Erro: " + str(e))
#     elif family == "sdxl":
#         try:
#             pipe = StableDiffusionXLPipeline.from_single_file(model_path, torch_dtype=dtype, use_safetensors=is_st, safety_checker=None, requires_safety_checker=False)
#         except Exception:
#             print("Injetando Text Encoders + VAE do SDXL base...")
#             te1 = CLIPTextModel.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="text_encoder", torch_dtype=dtype)
#             te2 = CLIPTextModelWithProjection.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="text_encoder_2", torch_dtype=dtype)
#             tok1 = CLIPTokenizer.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="tokenizer")
#             tok2 = CLIPTokenizer.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="tokenizer_2")
#             vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=dtype)
#             pipe = StableDiffusionXLPipeline.from_single_file(model_path, text_encoder=te1, text_encoder_2=te2, tokenizer=tok1, tokenizer_2=tok2, vae=vae, torch_dtype=dtype, use_safetensors=is_st, safety_checker=None, requires_safety_checker=False)
#     elif family in ("sd15", "sd2"):
#         try:
#             pipe = StableDiffusionPipeline.from_single_file(model_path, torch_dtype=dtype, use_safetensors=is_st, safety_checker=None, requires_safety_checker=False)
#         except Exception:
#             print("Injetando Text Encoder + VAE do SD 1.5 base...")
#             te = CLIPTextModel.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="text_encoder", torch_dtype=dtype)
#             tok = CLIPTokenizer.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="tokenizer")
#             vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse", torch_dtype=dtype)
#             pipe = StableDiffusionPipeline.from_single_file(model_path, text_encoder=te, tokenizer=tok, vae=vae, torch_dtype=dtype, use_safetensors=is_st, safety_checker=None, requires_safety_checker=False)
#     elif family == "anima":
#         try:
#             from diffusers import AnimaPipeline
#             pipe = AnimaPipeline.from_single_file(model_path, torch_dtype=dtype)
#         except Exception:
#             raise RuntimeError(_unsupported_family("anima", base_model))
#     elif family == "chroma":
#         try:
#             from diffusers import ChromaPipeline, ChromaTransformer2DModel
#             transformer = ChromaTransformer2DModel.from_single_file(model_path, torch_dtype=dtype)
#             pipe = ChromaPipeline.from_pretrained("lodestones/Chroma", transformer=transformer, torch_dtype=dtype)
#         except Exception as e:
#             raise RuntimeError("Chroma (experimental) falhou: " + str(e))
#     elif family == "zimage":
#         try:
#             from diffusers import ZImagePipeline, ZImageTransformer2DModel
#             transformer = ZImageTransformer2DModel.from_single_file(model_path, torch_dtype=dtype)
#             pipe = ZImagePipeline.from_pretrained("Tongyi-MAI/Z-Image-Turbo", transformer=transformer, torch_dtype=dtype)
#         except Exception as e:
#             raise RuntimeError("Z-Image (experimental) falhou: " + str(e))
#     else:
#         raise RuntimeError(_unsupported_family(family, base_model))
# 
#     offload_mode = cfg.get("cpu_offload", "model")
#     if offload_mode == "sequential":
#         try: pipe.enable_sequential_cpu_offload()
#         except Exception:
#             try: pipe.enable_model_cpu_offload()
#             except Exception: pipe.to("cuda")
#     elif offload_mode == "model":
#         try: pipe.enable_model_cpu_offload()
#         except Exception: pipe.to("cuda")
#     else:
#         try: pipe.to("cuda")
#         except Exception: pass
#     try:
#         if hasattr(pipe, "vae") and pipe.vae is not None:
#             pipe.vae.enable_slicing()
#             pipe.vae.enable_tiling()
#     except Exception:
#         pass
#     STATE["pipe"] = pipe
#     STATE["backend"] = "single_file"
#     STATE["loaded"] = True
# 
# def load_wan2gp_krea(cfg):
#     sys.path.insert(0, WAN2GP_DIR)
#     from mmgp import offload
#     from shared.utils import files_locator as fl
#     from models.krea2.krea2_handler import family_handler
#     paths = cfg.get("paths")
#     if not paths:
#         raise ValueError("Para modelos wan2gp_krea2, o registry precisa conter 'paths'.")
#     fl.set_checkpoints_paths([MODELS_DIR, os.path.join(WAN2GP_DIR, "ckpts"), WAN2GP_DIR, "."])
#     transformer_path = paths["transformer"]
#     text_encoder_path = paths["text_encoder"]
#     if not os.path.exists(transformer_path):
#         raise FileNotFoundError("Transformer nao encontrado em " + transformer_path)
#     if not os.path.exists(text_encoder_path):
#         raise FileNotFoundError("Text encoder nao encontrado em " + text_encoder_path)
#     dtype = get_torch_dtype(cfg.get("dtype", "float16"))
#     vae_dtype = get_torch_dtype(cfg.get("vae_dtype", "float16"))
#     old_cwd = os.getcwd()
#     os.chdir(WAN2GP_DIR)
#     try:
#         base_model_type = cfg.get("base_model_type", "krea2_turbo")
#         model_type = cfg.get("model_type", "krea2_turbo")
#         model_def = family_handler.query_model_def(base_model_type, {})
#         krea_model, pipe = family_handler.load_model(
#             model_filename=transformer_path, model_type=model_type,
#             base_model_type=base_model_type, model_def=model_def,
#             quantizeTransformer=cfg.get("quantize_transformer", False),
#             dtype=dtype, VAE_dtype=vae_dtype,
#             text_encoder_filename=text_encoder_path,
#         )
#         offload_cfg = cfg.get("offload", {})
#         offload.profile(
#             pipe, profile_no=offload_cfg.get("profile_no", 2),
#             quantizeTransformer=cfg.get("quantize_transformer", False),
#             convertWeightsFloatTo=dtype,
#             pinnedMemory=offload_cfg.get("pinnedMemory", False),
#             asyncTransfers=offload_cfg.get("asyncTransfers", False),
#             budgets=offload_cfg.get("budgets", {"transformer": 10000, "text_encoder": 4000, "vae": 1500, "*": 500}),
#         )
#         offload.shared_state["_attention"] = cfg.get("attention", "sdpa")
#         STATE["krea_model"] = krea_model
#         STATE["pipe"] = pipe
#         STATE["backend"] = "wan2gp_krea2"
#         STATE["loaded"] = True
#     finally:
#         os.chdir(old_cwd)
# 
# def load_model(cfg):
#     unload_current_model()
#     backend = cfg.get("backend", "auto")
#     if backend == "wan2gp_krea2": load_wan2gp_krea(cfg)
#     elif backend == "diffusers": load_diffusers(cfg)
#     elif backend == "single_file": load_single_file(cfg)
#     else: raise ValueError("Backend nao suportado: " + str(backend))
#     STATE["config"] = cfg
#     gc.collect()
#     torch.cuda.empty_cache()
# 
# def model_ui_settings(model_name):
#     reg = load_registry()
#     cfg = reg.get(model_name, {})
#     if not cfg:
#         return (gr.update(), gr.update(), gr.update(), gr.update(), gr.update(), "")
#     steps = cfg.get("steps", {"min": 1, "max": 30, "default": 8})
#     images = cfg.get("images", {"min": 1, "max": 1, "default": 1})
#     return (
#         gr.update(minimum=steps.get("min", 1), maximum=steps.get("max", 30), value=steps.get("default", 8)),
#         gr.update(minimum=images.get("min", 1), maximum=images.get("max", 1), value=images.get("default", 1)),
#         gr.update(choices=cfg.get("resolutions", ["1024px (Standard)"]), value=cfg.get("default_resolution", "1024px (Standard)")),
#         gr.update(choices=cfg.get("aspect_ratios", ["1:1 Square"]), value=cfg.get("default_aspect_ratio", "1:1 Square")),
#         gr.update(value=float(cfg.get("guide_scale", 0.0))),
#         cfg.get("warning", "")
#     )
# 
# def initial_ui():
#     choices = registry_choices()
#     value = choices[0] if choices else None
#     return [gr.update(choices=choices, value=value)] + list(model_ui_settings(value))
# 
# def detect_selected_model(model_name, token):
#     try:
#         msg_login = hf_login(token) if token else ""
#         reg = load_registry()
#         cfg = reg.get(model_name)
#         if not cfg: return "Modelo nao encontrado."
#         repo = pick_repo_for_t4(cfg)
#         backend = detect_backend(repo)
#         msg = "Modelo: " + model_name + "\nRepo: " + repo + "\nBackend: " + backend
#         if msg_login: msg = msg_login + "\n\n" + msg
#         return msg
#     except Exception as e:
#         return "Erro ao detectar: " + str(e)
# 
# def download_and_load_model(model_name, token):
#     try:
#         if token: hf_login(token)
#         reg = load_registry()
#         cfg = reg.get(model_name)
#         if not cfg:
#             return ["Modelo nao encontrado."] + [gr.update()] * 6
#         cfg = cfg.copy()
#         cfg["name"] = model_name
#         cfg["selected_repo"] = pick_repo_for_t4(cfg)
#         if cfg.get("backend", "auto") in [None, "", "auto"]:
#             cfg["backend"] = detect_backend(cfg["selected_repo"])
#         cfg = ensure_downloaded(cfg)
#         load_model(cfg)
#         status = "Modelo carregado: " + model_name + "\nRepo: " + str(cfg.get('selected_repo')) + "\nBackend: " + str(cfg.get('backend'))
#         return [status] + list(model_ui_settings(model_name))
#     except Exception as e:
#         traceback.print_exc()
#         return ["Erro: " + str(e)] + [gr.update()] * 6
# 
# def load_civitai_model(url_or_id, token):
#     try:
#         if not url_or_id or not url_or_id.strip():
#             return "Insira a URL ou ID do modelo.", gr.update(), gr.update(), gr.update(), gr.update(), gr.update()
#         local_path, base_model, model_name = download_from_civitai(url_or_id.strip(), token)
#         cfg = {
#             "label": "Civitai: " + model_name,
#             "backend": "single_file", "model_path": local_path,
#             "base_model_type": base_model, "dtype": "float16",
#             "cpu_offload": "model",
#             "supports_negative": True, "supports_guidance": True,
#             "guide_scale": 7.0 if "flux" not in base_model.lower() else 0.0,
#             "steps": {"min": 1, "max": 30, "default": 20 if "flux" not in base_model.lower() else 4},
#             "images": {"min": 1, "max": 1, "default": 1},
#             "resolutions": ["512px (Fast)", "768px (Balanced)", "1024px (High)"],
#             "default_resolution": "768px (Balanced)" if any(k in base_model.lower() for k in ["sdxl", "pony", "anima", "illustrious", "noobai"]) else "512px (Fast)",
#             "aspect_ratios": ["1:1 Square", "16:9 Landscape", "9:16 Portrait"],
#             "default_aspect_ratio": "1:1 Square",
#             "warning": "Modelo Civitai. Base: " + base_model
#         }
#         if "flux" in base_model.lower():
#             cfg["cpu_offload"] = "sequential"
#             cfg["default_resolution"] = "768px (Low VRAM)"
#             cfg["resolutions"] = ["512px (Fast)", "768px (Low VRAM)", "1024px (Standard)"]
#         load_model(cfg)
#         status = "Modelo Civitai carregado: " + model_name + "\nBase Model: " + base_model + "\nCaminho: " + os.path.basename(local_path) + "\nVa para a aba Gerar!"
#         steps_cfg = cfg.get("steps", {"min": 1, "max": 30, "default": 8})
#         images_cfg = cfg.get("images", {"min": 1, "max": 1, "default": 1})
#         return (status,
#             gr.update(minimum=steps_cfg["min"], maximum=steps_cfg["max"], value=steps_cfg["default"]),
#             gr.update(minimum=images_cfg["min"], maximum=images_cfg["max"], value=images_cfg["default"]),
#             gr.update(choices=cfg["resolutions"], value=cfg["default_resolution"]),
#             gr.update(choices=cfg["aspect_ratios"], value=cfg["default_aspect_ratio"]),
#             gr.update(value=cfg["guide_scale"]))
#     except Exception as e:
#         traceback.print_exc()
#         return "Erro ao carregar do Civitai: " + str(e), gr.update(), gr.update(), gr.update(), gr.update(), gr.update()
# 
# def apply_lora(lora_source, weight):
#     try:
#         if not STATE.get("loaded"):
#             return "Nenhum modelo carregado."
#         if STATE.get("backend") not in ["diffusers", "single_file"]:
#             return "LoRA suportado apenas para modelos Diffusers."
#         pipe = STATE.get("pipe")
#         if pipe is None: return "Pipeline nao disponivel."
#         lora_source = (lora_source or "").strip()
#         if not lora_source:
#             try:
#                 pipe.unload_lora_weights()
#                 STATE["lora_name"] = None
#                 STATE["lora_scale"] = 0.0
#                 return "LoRA removido."
#             except Exception as e:
#                 return "Falha ao remover LoRA: " + str(e)
#         if os.path.exists(lora_source):
#             pipe.load_lora_weights(lora_source)
#             STATE["lora_name"] = lora_source
#         else:
#             if "/" in lora_source and lora_source.lower().endswith((".safetensors", ".ckpt", ".pt")):
#                 repo_id, weight_name = lora_source.split("/", 1)
#                 pipe.load_lora_weights(repo_id, weight_name=weight_name)
#                 STATE["lora_name"] = repo_id + ":" + weight_name
#             else:
#                 pipe.load_lora_weights(lora_source)
#                 STATE["lora_name"] = lora_source
#         STATE["lora_scale"] = float(weight)
#         try:
#             pipe.set_adapters(["default"], adapter_weights=[float(weight)])
#         except Exception:
#             pass
#         return "LoRA aplicado: " + str(STATE['lora_name']) + " | peso: " + str(STATE['lora_scale'])
#     except Exception as e:
#         traceback.print_exc()
#         return "Erro ao aplicar LoRA: " + str(e)
# 
# def _enhance(prompt, style_preset="None"):
#     if not prompt: return ""
#     p = prompt.lower()
#     if any(k in p for k in ["photorealistic", "hyperrealistic", "highly detailed", "8k resolution"]):
#         enhanced = prompt
#     elif any(w in p for w in ["person", "woman", "man", "girl", "boy", "portrait", "face"]):
#         enhanced = prompt + ", 85mm lens, f/1.8, natural skin texture, professional studio lighting, highly detailed, 8k"
#     elif any(w in p for w in ["cyberpunk", "futuristic", "sci-fi", "robot", "neon"]):
#         enhanced = prompt + ", cyberpunk aesthetic, neon glow, volumetric fog, cinematic lighting, ray tracing, 8k"
#     elif any(w in p for w in ["forest", "mountain", "ocean", "landscape", "lake", "river", "sky", "sunset"]):
#         enhanced = prompt + ", golden hour, national geographic style, volumetric mist, wide-angle lens, 8k"
#     elif any(w in p for w in ["dragon", "magic", "wizard", "elf", "castle", "fantasy"]):
#         enhanced = prompt + ", glowing magical particles, ethereal light, highly detailed fantasy art, 8k"
#     elif any(w in p for w in ["anime", "illustration", "drawing", "painting", "digital art"]):
#         enhanced = prompt + ", vibrant color palette, clean line art, beautiful lighting, anime key visual, masterpiece"
#     else:
#         enhanced = prompt + ", highly detailed, photorealistic, cinematic lighting, masterpiece, 8k"
#     styles = {
#         "Cinematic": "cinematic lighting, dramatic shadows, film grain, masterpiece",
#         "Photographic": "professional photography, 35mm lens, f/2.8, depth of field, photorealistic",
#         "Anime": "anime key visual, vibrant color palette, clean line art, highly detailed",
#         "Cyberpunk": "cyberpunk aesthetic, neon lights, volumetric smoke, high contrast",
#         "Fantasy": "mythical atmosphere, glowing particles, ethereal light, digital painting",
#     }
#     if style_preset and style_preset != "None" and style_preset in styles:
#         enhanced += ", " + styles[style_preset]
#     return enhanced
# 
# def _parse_px(value, default=1024):
#     try:
#         if isinstance(value, (int, float)): return int(value)
#         return int(str(value).split("px")[0].strip())
#     except Exception:
#         return default
# 
# def _dims(aspect, base):
#     b = _parse_px(base, 1024)
#     if aspect == "1:1 Square": return b, b
#     elif aspect == "16:9 Landscape": return b, max(16, int((b * 9 / 16) // 16 * 16))
#     elif aspect == "9:16 Portrait": return max(16, int((b * 9 / 16) // 16 * 16)), b
#     elif aspect == "4:3 Standard": return b, max(16, int((b * 3 / 4) // 16 * 16))
#     elif aspect == "3:4 Portrait": return max(16, int((b * 3 / 4) // 16 * 16)), b
#     return b, b
# 
# def backend_generate(seed, prompt, negative_prompt, steps, width, height, guidance_scale, callback=None):
#     backend = STATE.get("backend")
#     if backend == "wan2gp_krea2":
#         krea_model = STATE.get("krea_model")
#         if krea_model is None: raise RuntimeError("Krea model nao carregado.")
#         result = krea_model.generate(
#             seed=int(seed), input_prompt=prompt,
#             n_prompt=negative_prompt.strip() or None,
#             sampling_steps=int(steps), width=int(width), height=int(height),
#             guide_scale=float(guidance_scale), batch_size=1,
#             callback=callback, loras_slists={"phase1": []},
#         )
#         if result is None: raise RuntimeError("Geracao retornou None.")
#         img = Image.fromarray(result[:, 0].permute(1, 2, 0).numpy())
#         del result
#         gc.collect(); torch.cuda.empty_cache()
#         return img
#     elif backend in ["diffusers", "single_file"]:
#         pipe = STATE.get("pipe")
#         if pipe is None: raise RuntimeError("Pipeline Diffusers nao carregado.")
#         generator = torch.Generator(device="cuda").manual_seed(int(seed))
#         kwargs = {
#             "prompt": prompt, "num_inference_steps": int(steps),
#             "width": int(width), "height": int(height),
#             "generator": generator,
#         }
#         cfg = STATE.get("config") or {}
#         if cfg.get("supports_negative", True) and negative_prompt:
#             kwargs["negative_prompt"] = negative_prompt
#         if cfg.get("supports_guidance", True):
#             kwargs["guidance_scale"] = float(guidance_scale)
#         if STATE.get("lora_scale", 0.0) not in [None, 0.0]:
#             try:
#                 sig = inspect.signature(pipe.__call__)
#                 if "cross_attention_kwargs" in sig.parameters:
#                     kwargs["cross_attention_kwargs"] = {"scale": float(STATE["lora_scale"])}
#             except Exception:
#                 pass
#         try:
#             sig = inspect.signature(pipe.__call__)
#             if "negative_prompt" not in sig.parameters: kwargs.pop("negative_prompt", None)
#             if "guidance_scale" not in sig.parameters: kwargs.pop("guidance_scale", None)
#             if "cross_attention_kwargs" not in sig.parameters: kwargs.pop("cross_attention_kwargs", None)
#         except Exception:
#             pass
#         result = None
#         if callback is not None:
#             try:
#                 sig = inspect.signature(pipe.__call__)
#                 if "callback_on_step_end" in sig.parameters:
#                     def step_cb(pipe_obj, step_index, timestep, callback_kwargs):
#                         callback(step_index, None, False)
#                         return callback_kwargs
#                     result = pipe(callback_on_step_end=step_cb, **kwargs)
#                 else:
#                     result = pipe(**kwargs)
#             except TypeError:
#                 result = pipe(**kwargs)
#         else:
#             result = pipe(**kwargs)
#         if result is None or not hasattr(result, "images") or len(result.images) == 0:
#             raise RuntimeError("Geracao Diffusers nao retornou imagens.")
#         img = result.images[0]
#         del result
#         gc.collect(); torch.cuda.empty_cache()
#         return img
#     else:
#         raise RuntimeError("Nenhum backend carregado.")
# 
# @torch.inference_mode()
# def generate(prompt, negative_prompt, steps, aspect_ratio, resolution, seed, num_images, guidance_scale, progress=gr.Progress(track_tqdm=True)):
#     try:
#         if not STATE.get("loaded"):
#             yield gr.update(value=None, selected_index=None), "Nenhum modelo carregado. Use a aba Modelo.", gr.update(visible=False)
#             return
#         gc.collect(); torch.cuda.empty_cache()
#         yield gr.update(value=None, selected_index=None), "Starting...", gr.update(visible=False)
#         width, height = _dims(aspect_ratio, resolution)
#         init_seed = random.randint(0, 2**32 - 1) if (seed is None or seed < 0) else int(seed)
#         images, seeds_used = [], []
#         t0 = time.time()
#         num_images = int(num_images); steps = int(steps)
#         for i in range(num_images):
#             s = (init_seed + i) % (2**32); seeds_used.append(s)
#             print("Generating image " + str(i+1) + "/" + str(num_images) + ": " + str(width) + "x" + str(height) + ", steps=" + str(steps) + ", seed=" + str(s))
#             sys.stdout.flush()
#             def cb(step_idx, latent, is_start, override_num_inference_steps=None, **kw):
#                 pct = (i + (step_idx + 1) / max(1, steps)) / max(1, num_images)
#                 progress(min(pct, 0.99), desc="Image " + str(i+1) + "/" + str(num_images) + " - step " + str(step_idx + 1) + "/" + str(steps))
#             progress((i) / max(1, num_images), desc="Preparing image " + str(i+1) + "/" + str(num_images) + "...")
#             img = backend_generate(seed=s, prompt=prompt, negative_prompt=negative_prompt, steps=steps, width=width, height=height, guidance_scale=guidance_scale, callback=cb)
#             images.append(img)
#             gc.collect(); torch.cuda.empty_cache()
#             yield gr.update(value=images, selected_index=0), "Generated " + str(len(images)) + "/" + str(num_images) + "...", gr.update(visible=False)
#         zip_path = None
#         if len(images) > 1:
#             import zipfile, tempfile
#             tmp = tempfile.NamedTemporaryFile(suffix=".zip", delete=False)
#             zip_path = tmp.name
#             model_label = (STATE.get("config") or {}).get("label", "model")
#             safe_label = model_label.replace(" ", "_").lower()
#             with zipfile.ZipFile(zip_path, "w") as zf:
#                 for idx, img in enumerate(images):
#                     p = tempfile.mktemp(suffix=".png")
#                     img.save(p)
#                     zf.write(p, safe_label + "_" + str(idx+1) + "_seed" + str(seeds_used[idx]) + ".png")
#                     try: os.remove(p)
#                     except Exception: pass
#         elapsed = time.time() - t0
#         status = "OK " + str(len(images)) + " image(s) in " + "{:.1f}".format(elapsed) + "s | Seeds: " + str(seeds_used) + " | " + str(width) + "x" + str(height)
#         yield gr.update(value=images, selected_index=0), status, gr.update(value=zip_path, visible=(zip_path is not None))
#     except Exception as e:
#         traceback.print_exc()
#         gc.collect(); torch.cuda.empty_cache()
#         yield gr.update(value=None, selected_index=None), "Error: " + str(e), gr.update(visible=False)
# 
# def save_new_model(label, repo, t4_repo, backend, dtype, cpu_offload, steps_min, steps_max, steps_default, guidance_default, resolutions, default_resolution, aspects, default_aspect, supports_negative, supports_guidance):
#     try:
#         label = (label or "").strip()
#         repo = (repo or "").strip()
#         t4_repo = (t4_repo or "").strip()
#         if not label or not repo:
#             return "Nome e repo sao obrigatorios.", gr.update()
#         reg = load_registry()
#         res_list = [x.strip() for x in (resolutions or "").split(",") if x.strip()]
#         if not res_list: res_list = ["1024px (Standard)"]
#         asp_list = [x.strip() for x in (aspects or "").split(",") if x.strip()]
#         if not asp_list: asp_list = ["1:1 Square"]
#         folder_name = label.lower().replace(" ", "-").replace("/", "-")
#         reg[label] = {
#             "label": label, "repo": repo, "t4_repo": t4_repo,
#             "t4_repo_candidates": [t4_repo, repo] if t4_repo else [repo],
#             "backend": backend or "auto", "folder_name": folder_name,
#             "dtype": dtype or "float16", "cpu_offload": cpu_offload or "model",
#             "use_safetensors": True, "supports_negative": bool(supports_negative),
#             "supports_guidance": bool(supports_guidance),
#             "guide_scale": float(guidance_default or 0.0),
#             "steps": {"min": int(steps_min or 1), "max": int(steps_max or 30), "default": int(steps_default or 8)},
#             "images": {"min": 1, "max": 1, "default": 1},
#             "resolutions": res_list,
#             "default_resolution": (default_resolution or res_list[0]).strip(),
#             "aspect_ratios": asp_list,
#             "default_aspect_ratio": (default_aspect or asp_list[0]).strip(),
#             "styles": STYLES, "ignore_patterns": COMMON_IGNORE,
#             "warning": "Modelo adicionado manualmente."
#         }
#         save_registry(reg)
#         choices = list(reg.keys())
#         return "Modelo '" + label + "' salvo no registry.", gr.update(choices=choices, value=label)
#     except Exception as e:
#         traceback.print_exc()
#         return "Erro ao salvar modelo: " + str(e), gr.update()
# 
# def clear_all():
#     cfg = STATE.get("config") or {}
#     steps = cfg.get("steps", {"default": 8})
#     images = cfg.get("images", {"default": 1})
#     return ("", "", steps.get("default", 8),
#         cfg.get("default_aspect_ratio", "1:1 Square"),
#         cfg.get("default_resolution", "1024px (Standard)"),
#         -1, images.get("default", 1), "None",
#         float(cfg.get("guide_scale", 0.0)),
#         gr.update(value=None, selected_index=None), "", gr.update(visible=False))
# 
# CIVITAI_EXAMPLES = [
#     "Arthemy Comics Anima (2700278)",
#     "Arthemy Comics Illustrious (1273254)",
#     "Arthemy Western Art (2241572)",
#     "Arthemy Comics Krea2 (2759057)",
#     "Arthemy Toons Illustrious (1906150)",
#     "Arthemy Anime (2442462)",
#     "Arthemy Comics (54073)",
#     "A-Zovya RPG Artist Tools (8124)",
#     "Childrens Stories Toolkit (64544)",
#     "Kestral Flux Anime (697877)",
#     "Kestral PNY (623819)",
#     "Cor Epica (552880)"
# ]
# 
# CIVITAI_URL_MAP = {
#     "Arthemy Comics Anima (2700278)": "https://civitai.com/models/2700278",
#     "Arthemy Comics Illustrious (1273254)": "https://civitai.com/models/1273254",
#     "Arthemy Western Art (2241572)": "https://civitai.com/models/2241572",
#     "Arthemy Comics Krea2 (2759057)": "https://civitai.com/models/2759057",
#     "Arthemy Toons Illustrious (1906150)": "https://civitai.com/models/1906150",
#     "Arthemy Anime (2442462)": "https://civitai.com/models/2442462",
#     "Arthemy Comics (54073)": "https://civitai.com/models/54073",
#     "A-Zovya RPG Artist Tools (8124)": "https://civitai.com/models/8124",
#     "Childrens Stories Toolkit (64544)": "https://civitai.com/models/64544",
#     "Kestral Flux Anime (697877)": "https://civitai.com/models/697877",
#     "Kestral PNY (623819)": "https://civitai.com/models/623819",
#     "Cor Epica (552880)": "https://civitai.com/models/552880"
# }
# 
# def update_civitai_url(choice):
#     if choice in CIVITAI_URL_MAP: return CIVITAI_URL_MAP[choice]
#     return ""
# 
# with gr.Blocks(theme=gr.themes.Soft(), title="Advanced Multi-Model Image Studio") as demo:
#     gr.Markdown("# Advanced Multi-Model Image Studio")
#     gr.Markdown("Suporte a Civitai, Hugging Face, Krea-2-Turbo, FLUX, SDXL, Pony, Illustrious, NoobAI, Animagine, SD3, Anima, Chroma, Z-Image e mais.")
# 
#     with gr.Tabs():
#         with gr.TabItem("Modelo / Configuracao"):
#             hf_token = gr.Textbox(label="Hugging Face Token (opcional)", type="password", placeholder="Cole aqui se o modelo exigir login/licenca")
#             model_dropdown = gr.Dropdown(label="Modelo (Hugging Face / Wan2GP)", choices=registry_choices(), value=registry_choices()[0] if registry_choices() else None, allow_custom_value=True)
#             model_warning = gr.Markdown("")
#             with gr.Row():
#                 detect_btn = gr.Button("Detectar backend", variant="secondary")
#                 load_btn = gr.Button("Baixar e carregar (HF)", variant="primary")
#                 refresh_btn = gr.Button("Atualizar lista", variant="secondary")
#             manager_status = gr.Textbox(label="Status", lines=6)
# 
#             gr.Markdown("---")
#             gr.Markdown("### Civitai Downloader")
#             gr.Markdown("Baixe qualquer modelo do Civitai. O app detecta automaticamente: SD 1.5, SDXL, Pony, Illustrious, NoobAI, Animagine, FLUX, SD3, Anima, Chroma, Z-Image, etc.")
#             with gr.Row():
#                 civitai_examples = gr.Dropdown(label="Exemplos Populares", choices=[""] + CIVITAI_EXAMPLES, value="")
#             civitai_url = gr.Textbox(label="URL ou ID do Modelo no Civitai", placeholder="https://civitai.com/models/12345 ou apenas 12345")
#             civitai_token = gr.Textbox(label="Civitai API Token (Recomendado)", type="password", placeholder="Cole seu token do Civitai aqui")
#             civitai_load_btn = gr.Button("Baixar do Civitai e Carregar", variant="primary")
#             civitai_status = gr.Textbox(label="Status Civitai", lines=4)
# 
#             with gr.Accordion("LoRA (apos carregar modelo Diffusers)", open=False):
#                 lora_source = gr.Textbox(label="LoRA (caminho local ou repo HF)", placeholder="Ex: /content/lora.safetensors ou usuario/lora-repo/lora.safetensors")
#                 lora_weight = gr.Slider(0.0, 2.0, 1.0, step=0.05, label="LoRA Weight")
#                 apply_lora_btn = gr.Button("Aplicar LoRA", variant="primary")
#                 lora_status = gr.Textbox(label="LoRA Status", lines=2)
# 
#             with gr.Accordion("Adicionar novo modelo sem mexer no codigo", open=False):
#                 admin_label = gr.Textbox(label="Nome do modelo", placeholder="Ex: Meu SDXL Custom")
#                 admin_repo = gr.Textbox(label="Repo HF", placeholder="usuario/modelo")
#                 admin_t4_repo = gr.Textbox(label="Repo T4/quantizado opcional", placeholder="usuario/modelo-int8")
#                 admin_backend = gr.Dropdown(["auto", "diffusers", "wan2gp_krea2", "single_file"], value="auto", label="Backend")
#                 admin_dtype = gr.Dropdown(["float16", "bfloat16", "float32"], value="float16", label="Dtype")
#                 admin_offload = gr.Dropdown(["model", "sequential", "none"], value="model", label="CPU Offload")
#                 with gr.Row():
#                     admin_steps_min = gr.Number(1, label="Steps min")
#                     admin_steps_max = gr.Number(30, label="Steps max")
#                     admin_steps_default = gr.Number(8, label="Steps default")
#                     admin_guidance = gr.Number(0.0, label="Guidance default")
#                 admin_resolutions = gr.Textbox(label="Resolucoes (virgula)", value="512px (Fast),768px (Balanced),1024px (High)")
#                 admin_default_resolution = gr.Textbox(label="Resolucao default", value="768px (Balanced)")
#                 admin_aspects = gr.Textbox(label="Aspect ratios (virgula)", value="1:1 Square,16:9 Landscape,9:16 Portrait")
#                 admin_default_aspect = gr.Textbox(label="Aspect ratio default", value="1:1 Square")
#                 admin_negative = gr.Checkbox(True, label="Suporta Negative Prompt")
#                 admin_guidance_support = gr.Checkbox(True, label="Suporta Guidance Scale")
#                 admin_save_btn = gr.Button("Salvar novo modelo", variant="primary")
#                 admin_status = gr.Textbox(label="Admin Status", lines=2)
# 
#         with gr.TabItem("Gerar"):
#             with gr.Row():
#                 with gr.Column(scale=3):
#                     prompt = gr.Textbox(label="Prompt", lines=3, placeholder="A small dark cat walking down an abandoned cobblestone street at dusk...")
#                     with gr.Row():
#                         enhance_btn = gr.Button("Enhance Prompt", variant="secondary")
#                         style_preset = gr.Dropdown(STYLES, value="None", label="Style Preset")
#                     with gr.Row():
#                         aspect_ratio = gr.Dropdown(["1:1 Square", "16:9 Landscape", "9:16 Portrait"], value="1:1 Square", label="Aspect Ratio")
#                         resolution = gr.Dropdown(["512px (Fast)", "768px (Balanced)", "1024px (Standard)"], value="768px (Balanced)", label="Resolution")
#                     with gr.Row():
#                         steps = gr.Slider(1, 30, 8, step=1, label="Steps")
#                         num_images = gr.Slider(1, 1, 1, step=1, label="Images")
#                     with gr.Accordion("Advanced", open=False):
#                         negative_prompt = gr.Textbox(label="Negative Prompt", placeholder="low quality, blurry, distorted, bad anatomy", lines=2)
#                         seed = gr.Number(-1, label="Seed (-1 = random)", precision=0)
#                         guidance_scale = gr.Slider(0.0, 20.0, 0.0, step=0.5, label="Guidance Scale")
#                     with gr.Row():
#                         gen_btn = gr.Button("Generate", variant="primary", size="lg")
#                         clear_btn = gr.Button("Clear", variant="secondary", size="lg")
#                 with gr.Column(scale=1):
#                     gallery = gr.Gallery(label="Output", columns=2, rows=2, object_fit="contain", preview=True)
#                     zip_out = gr.File(label="Download ZIP", visible=False)
#                     status_out = gr.Textbox(label="Status", interactive=False)
# 
#     demo.load(fn=initial_ui, outputs=[model_dropdown, steps, num_images, resolution, aspect_ratio, guidance_scale, model_warning])
#     model_dropdown.change(fn=model_ui_settings, inputs=[model_dropdown], outputs=[steps, num_images, resolution, aspect_ratio, guidance_scale, model_warning])
#     refresh_btn.click(fn=refresh_model_dropdown, outputs=[model_dropdown])
#     detect_btn.click(fn=detect_selected_model, inputs=[model_dropdown, hf_token], outputs=[manager_status])
#     load_btn.click(fn=download_and_load_model, inputs=[model_dropdown, hf_token], outputs=[manager_status, steps, num_images, resolution, aspect_ratio, guidance_scale, model_warning])
#     civitai_examples.change(fn=update_civitai_url, inputs=[civitai_examples], outputs=[civitai_url])
#     civitai_load_btn.click(fn=load_civitai_model, inputs=[civitai_url, civitai_token], outputs=[civitai_status, steps, num_images, resolution, aspect_ratio, guidance_scale])
#     apply_lora_btn.click(fn=apply_lora, inputs=[lora_source, lora_weight], outputs=[lora_status])
#     admin_save_btn.click(fn=save_new_model, inputs=[admin_label, admin_repo, admin_t4_repo, admin_backend, admin_dtype, admin_offload, admin_steps_min, admin_steps_max, admin_steps_default, admin_guidance, admin_resolutions, admin_default_resolution, admin_aspects, admin_default_aspect, admin_negative, admin_guidance_support], outputs=[admin_status, model_dropdown])
#     enhance_btn.click(fn=lambda p, s: _enhance(p, s), inputs=[prompt, style_preset], outputs=[prompt])
#     gen_btn.click(fn=generate, inputs=[prompt, negative_prompt, steps, aspect_ratio, resolution, seed, num_images, guidance_scale], outputs=[gallery, status_out, zip_out])
#     clear_btn.click(fn=clear_all, outputs=[prompt, negative_prompt, steps, aspect_ratio, resolution, seed, num_images, style_preset, guidance_scale, gallery, status_out, zip_out])
# 
# print("Launching Advanced Multi-Model Image Studio...")
# demo.queue()
# demo.launch(share=True, inline=False, debug=True, show_error=True)

"""✅ Cell 3 — Validação"""

# ✅ Cell 3 — Validação de sintaxe
import ast
path = "/content/advanced_app.py"
try:
    with open(path, "r", encoding="utf-8") as f:
        source = f.read()
    ast.parse(source)
    print("OK advanced_app.py sintaxe valida")
    print("Tamanho: " + str(len(source)) + " caracteres")
    print("Execute a Cell 4 para iniciar!")
except SyntaxError as e:
    print("ERRO de sintaxe: " + str(e))
except FileNotFoundError:
    print("Arquivo advanced_app.py nao encontrado. Execute a Cell 2 primeiro.")

"""🚀 Cell 4 — Lançamento"""

# 🚀 Cell 4 — Launch!
!cd /content && python -u advanced_app.py 2>&1

# 🛠️ Patch: Suporte Experimental para Anima (CircleStone Labs)
import subprocess
import sys

print("=== Instalando suporte experimental para Anima ===")

# Tenta instalar o pacote comunitário diffusers-anima
try:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q",
        "--timeout", "120",
        "git+https://github.com/hdae/diffusers-anima.git"
    ])
    print("✅ diffusers-anima instalado com sucesso!")
except Exception as e:
    print(f"⚠️ Falha ao instalar diffusers-anima: {e}")
    print("ℹ️ Tentando método alternativo...")

# Agora aplica o patch no advanced_app.py
path = "/content/advanced_app.py"
with open(path, "r", encoding="utf-8") as f:
    src = f.read()

# Encontra e substitui a lógica de carregamento da Anima
old_anima_block = '''elif family == "anima":
        try:
            from diffusers import AnimaPipeline
            pipe = AnimaPipeline.from_single_file(model_path, torch_dtype=dtype)
        except Exception:
            raise RuntimeError(_unsupported_family("anima", base_model))'''

new_anima_block = '''elif family == "anima":
        try:
            # Tenta importar AnimaPipeline (pode estar em diffusers-anima)
            try:
                from diffusers import AnimaPipeline
                pipe = AnimaPipeline.from_single_file(model_path, torch_dtype=dtype)
                print("✅ Anima carregado via diffusers.AnimaPipeline")
            except ImportError:
                # Se não existir, tenta importar do pacote comunitário
                try:
                    from diffusers_anima import AnimaPipeline
                    pipe = AnimaPipeline.from_single_file(model_path, torch_dtype=dtype)
                    print("✅ Anima carregado via diffusers-anima")
                except ImportError:
                    # Último recurso: carrega do repositório Diffusers convertido
                    print("ℹ️ Anima single-file não suportado. Tentando carregar do repositório Diffusers convertido...")
                    from diffusers import StableDiffusionXLPipeline

                    # Anima usa arquitetura própria, mas alguns checkpoints são compatíveis com SDXL
                    # Tenta carregar como SDXL (pode falhar se a arquitetura for muito diferente)
                    try:
                        pipe = StableDiffusionXLPipeline.from_single_file(
                            model_path, torch_dtype=dtype, use_safetensors=is_st,
                            safety_checker=None, requires_safety_checker=False
                        )
                        print("✅ Anima carregado como SDXL (compatibilidade parcial)")
                    except Exception:
                        # Se tudo falhar, carrega do repo convertido
                        print("ℹ️ Carregando Anima do repositório Diffusers oficial...")
                        pipe = StableDiffusionXLPipeline.from_pretrained(
                            "circlestone-labs/Anima-Base-v1.0-Diffusers",
                            torch_dtype=dtype,
                            safety_checker=None,
                            requires_safety_checker=False
                        )
                        print("✅ Anima carregado do repositório Diffusers (não é o checkpoint do Civitai)")
        except Exception as e:
            raise RuntimeError(
                "Anima (CircleStone Labs, 2B) requer suporte experimental.\\n"
                "O Diffusers oficial ainda não suporta Anima nativamente.\\n"
                "Opções:\\n"
                "1. Use ComfyUI ou Forge Neo para checkpoints single-file\\n"
                "2. Use o modelo Diffusers convertido: circlestone-labs/Anima-Base-v1.0-Diffusers\\n"
                "Erro: " + str(e)
            )'''

if old_anima_block in src:
    src = src.replace(old_anima_block, new_anima_block)
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    print("✅ Patch aplicado! Anima agora tem suporte experimental.")
    print("👉 Pare a Cell 4 (Stop) e execute-a novamente.")
else:
    print("⚠️ Não foi possível encontrar o bloco exato. Verifique manualmente.")